### ISSUE TITLE
CSS remove arrows from input type="number" in globals.css

### ISSUE THREAD

**Issue by radoslavzeman** [bratislava/next-strapi-template#26]
```css
/* Remove arrows from input type='number' */
/* Chrome, Safari, Edge, Opera */
input[type='number']::-webkit-inner-spin-button,
input[type='number']::-webkit-outer-spin-button {
  -webkit-appearance: none;
  margin: 0;
}
/* Firefox */
input[type='number'] {
  -moz-appearance: textfield;
}
```
